# Generated by Django 4.2.1 on 2023-05-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_room_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
